### PR TITLE
Upgrade client for sregistry to use nginx upload module

### PR DESCRIPTION
**Pull request by vsoch**
This PR will close the following issues related to not being able to upload large containers:
  - #126 
  - #123 

This is the branch that should be used to test uploading to https://github.com/singularityhub/sregistry/pull/134 (the old method will no longer work)

I had originally planned to add chunked upload to Singularity Registry server. I did, and this was a web interface with a progress bar, etc. I was not happy with trying to get the same for an upload from the command line, so I scratched django chunked upload. Instead, I am using nginx upload module to (super speedily) upload files directly to the server from nginx.

In the code to do the push, you will now see two authentication checks. Both send an encrypted payload (with the user's token secret) to the server, and this payload is used to identify the user, check permissions, and finally authenticate the upload request. The first time a collection is returned (and permissions are checked) and we only continue if permissions are adequate. On the server the collection is created if the user has permission to do so and it doesn't exist, and of course a user that doesn't have permission cannot proceed beyond this point.

The second post uses multipart form encoded data to submit directly to the django_upload module, and the callback view then does the equivalent permissions checks, and only continues with processing the upload if everything is (still) ok. I suspect we will want some level of checking permissions on the level of the nginx module, but this can come later (and isn't relevant for this PR anyway).

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
I...can't seem to get this working to test  singularityhub/sregistry#134.
steps:
```bash
$ python3 -m venv sreg-test
$ cd sreg-test/
$ git clone https://github.com/singularityhub/sregistry-cli.git
$ cd sregistry-cli/
$ git fetch origin pull/127/head:add/chunked-upload
$ git checkout add/chunked-upload
$ source ../bin/activate.fish
$ python3 setup.py install
$sregistry images                                                                                                                                                                                            
WARNING Database disabled. Install sqlalchemy for full functionality
WARNING Singularity is not installed, function might be limited.
WARNING Singularity is not installed, function might be limited.
Traceback (most recent call last):
  File "/home/jensend/sreg-test/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.0.87', 'console_scripts', 'sregistry')()
  File "/home/jensend/sreg-test/lib/python3.6/site-packages/sregistry-0.0.87-py3.6.egg/sregistry/client/__init__.py", line 380, in main
    subparser=subparsers[args.command])
  File "/home/jensend/sreg-test/lib/python3.6/site-packages/sregistry-0.0.87-py3.6.egg/sregistry/client/images.py", line 33, in main
    cli.images(query=query)
AttributeError: 'Client' object has no attribute 'images'

**Comment by vsoch** [comment]
Taking a look!

**Comment by vsoch** [comment]
AH okay I see what is going on! Your virtual environment doesn't have sqlalchemy installed (see the first WARNING) and this is a valid use case given that you want to move containers around, but not store them in a database. The images command, however, is intended to show the containers in your database. So you should be able to install sqlalchemy to fix this issue, and what I need to do is put a meaningful error message to address this. Give me a few minutes and I'll see what I can do!

**Comment by vsoch** [comment]
okay I've just pushed a change that will remove the "images" command entirely as an option, given that sqlalchemy isn't installed.

**Comment by fearful-symmetry** [comment]
Ah, my bad. I assumed that `images` would reach out to the remote sregistry server. looks like the command I was searching for was `sregistry search`

**Comment by fearful-symmetry** [comment]
Alright, so it looks like image uploads via the web UI are working, however, we're having some issues using the CLI client:

```
[pid: 60566|app: 0|req: 88/88] 140.221.69.17 () {38 vars in 631 bytes} [Tue Jun 19 16:59:54 2018] GET /api/upload/chunked_upload => generated 850 bytes in 4 msecs (HTTP/1.1 500) 3 headers in 128 bytes (1 switches on core 0)
Internal Server Error: /api/upload/chunked_upload
Traceback (most recent call last):
  File "/opt/shub/sregistry/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/shub/sregistry/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/shub/sregistry/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/shub/sregistry/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/shub/sregistry/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "./shub/apps/api/actions/push.py", line 49, in collection_auth_check
    body = json.loads(body_unicode)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 
```

The `sregistry` CLI  client version is `0.0.87`

**Comment by vsoch** [comment]
@fearful-symmetry another thought that might be your issue - if you aren't supplying the name or are giving one that would weirdly result in "None" (e.g. --name) then the name could return a value of None and trigger an error like you are seeing. I would want to put in some check for this case (if it is the case!)

**Pull request merged**
