### PR TITLE
fixing undefined variable auth in docker

### LINKED ISSUE #192: auth undefined for docker client
Reported on gitter:

```
'sregistry backend activate docker
Traceback (most recent call last):
File "/opt/sregistry/sregistry-0.94/python/bin/sregistry", line 10, in <module>
sys.exit(main())
File "/opt/sregistry/sregistry-0.94/python/lib/python3.7/site-packages/sregistry/client/init.py", line 310, in main
from sregistry.main import Client as cli
File "/opt/sregistry/sregistry-0.94/python/lib/python3.7/site-packages/sregistry/main/init.py", line 118, in <module>
Client = get_client()
File "/opt/sregistry/sregistry-0.94/python/lib/python3.7/site-packages/sregistry/main/init.py", line 112, in get_client
cli = Client()
File "/opt/sregistry/sregistry-0.94/python/lib/python3.7/site-packages/sregistry/main/docker/init.py", line 42, in init
self._update_secrets()
File "/opt/sregistry/sregistry-0.94/python/lib/python3.7/site-packages/sregistry/main/docker/init.py", line 143, in _update_secrets
if credentials is not None and auth is None:
UnboundLocalError: local variable 'auth' referenced before assignment'
```

### PR DESCRIPTION
**Pull request by vsoch**
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

This will close #192

### CODE REVIEW

**Comment by vsoch** [comment]
@kanthsai143 please test.

**Comment by kanthsai143** [comment]
sregistry pull docker://ubuntu
WARNING Database disabled. Install sqlalchemy for full functionality
[client|docker] [database|dummy]
Traceback (most recent call last):
  File "/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.1.39', 'console_scripts', 'sregistry')()
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.39-py3.6.egg/sregistry/client/__init__.py", line 368, in main
    subparser=subparsers[args.command])
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.39-py3.6.egg/sregistry/client/pull.py", line 42, in main
    save=do_save)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.39-py3.6.egg/sregistry/main/docker/pull.py", line 74, in pull
    kwargs=kwargs)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.39-py3.6.egg/sregistry/main/docker/pull.py", line 118, in _pull
    file_name = self._get_storage_name(names)
  File "/usr/lib/python3.6/site-packages/sregistry-0.1.39-py3.6.egg/sregistry/main/base/settings.py", line 121, in get_storage_name
    storage_folder = "%s/%s" %(self.storage, storage_folder)
AttributeError: 'Client' object has no attribute 'storage'

**Comment by kanthsai143** [comment]
Hey
I am getting the following error now.

**Comment by vsoch** [comment]
You didn't install sqlalchemy so you don't have a database (the storage) - the warning is in the message you printed above. Is this your intention?

**Comment by vsoch** [comment]
I'm going to update the PR with a fix that should save the image to the PWD where you are doing the pull, give me one minute.

**Comment by vsoch** [comment]
okay updated.

**Comment by kanthsai143** [comment]
> You didn't install sqlalchemy so you don't have a database (the storage) - the warning is in the message you printed above. Is this your intention?

I did python setup.py install on this branch. Does it not install everything? Should I run a different command?

**Comment by kanthsai143** [comment]
`docker login
Authenticating with existing credentials...
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store`

Login Succeeded

I did the export
`export SREGISTRY_DOCKERHUB_SECRETS=/root/.docker/config.json`

Still can do the docker pull WARNING Database disabled. Install sqlalchemy for full functionality
`[client|docker] [database|dummy]
ERROR Your credentials are expired! Unauthorized: 401
ERROR Error getting token.
ERROR Error getting token.`

Another question. 

I made a collection private. When I try to pull it using singularity, I get the following error

`$singularity pull shub://myregistry.com/abc/def:latest`

WARNING: Authentication token file not found : Only pulls of public images will succeed
FATAL:   Invalid shub URI

**Comment by vsoch** [comment]
You'd want to do pip install .[all] to get all the dependencies.

**Comment by kanthsai143** [comment]
I found the culprit. It's in the sregistry server side. Can't believe I banged my head around this issue. 

I am copying the commands from the "usage" button. I just found the url is shown wrong in the singularity pull command. 

`singularity pull shub://myregistry.com/abc:def:latest`  **Actual shown**

`singularity pull shub://myregistry.com/abc/def:latest` **Command that works**

**Comment by vsoch** [comment]
Oy that's a bug, let me take a look.

**Comment by kanthsai143** [comment]
Will you be able to push this fix to master or should I just use this?

**Comment by vsoch** [comment]
I'll be able to update a PR that you can test, give me a minute.

**Comment by vsoch** [comment]
Just updated this PR for Singularity Registry, please test: https://github.com/singularityhub/sregistry/pull/188

**Comment by vsoch** [comment]
The other PR (for this repo) is good to go?

**Comment by kanthsai143** [comment]
Everything looks good now. But I can't test the sregistry server that easily, given that it took me a while to setup after doing customizations.

**Comment by vsoch** [comment]
https://pypi.org/project/sregistry/0.1.40/

**Comment by vsoch** [comment]
No worries @kanthsai143 - it's actually a fairly small change (and I've tested) so I'm going to go ahead and merge. Future users won't copy paste the wrong command :)

**Pull request merged**
