### PR TITLE
making changes to sregistry to add pull auth

### PR DESCRIPTION
**Pull request by vsoch**

### CODE REVIEW

**Comment by vsoch** [comment]
hey @victorsndvg! I did some tweaks to address the issue with pull/push and not having the secrets file (it should now give you an error message and exit before trying to get a None value for url) and I also did some reorganization of the base to address #33. I didn't get the time this morning to test this as robustly as I normally would (heading over to Dartmouth!) but I'll be back after some appointments and then have allll of tomorrow, so if you have time to test we can make some tiny progress, haha.

**Comment by victorsndvg** [comment]
Hi @vsoch ,

very busy this days, I was able to try this `sregistry-cli` status from the singularity container. Having the `.sregistry` file containing my token in my home folder i get the following error:

```
$ singularity run --app registry sregistry-cli pull mso4sc/example:latest
[client|registry] [database|sqlite:////home/vsande/.singularity/sregistry.db]
Traceback (most recent call last):
  File "/opt/conda/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry', 'console_scripts', 'sregistry')()
  File "/opt/sregistry-cli/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/opt/sregistry-cli/sregistry/client/pull.py", line 39, in main
    save=do_save)
  File "/opt/sregistry-cli/sregistry/main/registry/pull.py", line 61, in pull
    manifest = self._get(url)
  File "/opt/sregistry-cli/sregistry/main/base.py", line 214, in _get
    return_json=return_json)
  File "/opt/sregistry-cli/sregistry/main/base.py", line 322, in _call
    stream=stream)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'None/container/mso4sc/example:latest'
```

**Comment by victorsndvg** [comment]
Hi @vsoch ,

very busy this days, I was able to try this `sregistry-cli` status from the singularity container. Having the `.sregistry` file containing my token in my home folder i get the following error:

```
$ singularity run --app registry sregistry-cli pull mso4sc/example:latest
[client|registry] [database|sqlite:////home/vsande/.singularity/sregistry.db]
Traceback (most recent call last):
  File "/opt/conda/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry', 'console_scripts', 'sregistry')()
  File "/opt/sregistry-cli/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/opt/sregistry-cli/sregistry/client/pull.py", line 39, in main
    save=do_save)
  File "/opt/sregistry-cli/sregistry/main/registry/pull.py", line 61, in pull
    manifest = self._get(url)
  File "/opt/sregistry-cli/sregistry/main/base.py", line 214, in _get
    return_json=return_json)
  File "/opt/sregistry-cli/sregistry/main/base.py", line 322, in _call
    stream=stream)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'None/container/mso4sc/example:latest'
```

**Comment by vsoch** [comment]
hey @victorsndvg ! I haven't updated the Singularity container (provided) - you will need to build it locally from the Singularity file to test this (you are seeing the old error above).

**Comment by victorsndvg** [comment]
Yes, you are right.

This is the new error (I think):

```
# sregistry pull mso4sc/example
[client|registry] [database|sqlite:////root/.singularity/sregistry.db]
Traceback (most recent call last):
  File "/usr/local/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.0.5', 'console_scripts', 'sregistry')()
  File "/usr/local/lib/python3.6/site-packages/sregistry-0.0.5-py3.6.egg/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/usr/local/lib/python3.6/site-packages/sregistry-0.0.5-py3.6.egg/sregistry/client/pull.py", line 39, in main
    save=do_save)
  File "/usr/local/lib/python3.6/site-packages/sregistry-0.0.5-py3.6.egg/sregistry/main/registry/pull.py", line 65, in pull
    manifest = self._get(url)
  File "/usr/local/lib/python3.6/site-packages/sregistry-0.0.5-py3.6.egg/sregistry/main/base/http.py", line 73, in get
    return_json=return_json)
  File "/usr/local/lib/python3.6/site-packages/sregistry-0.0.5-py3.6.egg/sregistry/main/base/http.py", line 185, in call
    stream=stream)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'None/container/mso4sc/example:latest'
```

**Pull request merged**
