### PR TITLE
Development

### PR DESCRIPTION
**Pull request by iliaboti**
In case the current directory where sregistry pull is run from is in a different file system with the directory set with SREGISTRY_STORAGE then os.rename does not work. shutil.move will work.

### CODE REVIEW

**Comment by vsoch** [comment]
Yes this is a good change! I just read up on shutil.move vs. os.rename and it looks like the first uses the second for most cases, except when we have different filesystems. And it is more flexible! Would you like to make these changes also in:

```
sregistry/database/sqlite.py:            os.rename(image_path, storage_path)
sregistry/main/workers/tasks.py:        os.rename(tar_download, destination)
sregistry/main/docker/api.py:        os.rename(tar_download, download_folder)
```

(that was with `grep -R "os.rename"`

and add a note to the CHANGELOG saying we made the change for these reasons? Then I think we are good to go!

**Comment by iliaboti** [comment]
Sure I can do that. I was not sure if this is OK before since I have not
tested that path before.
It will be ready soon.

Thanks,
Ioannis

**Comment by vsoch** [comment]
yep, you got it :)

**Comment by vsoch** [comment]
haha and you did :) Let me see if I can resolve the conflicts.

**Comment by vsoch** [comment]
Hey did you mean to close this? Are there other changes you'd like to do?

**Comment by vsoch** [comment]
For record, this fix has been integrated via https://github.com/singularityhub/sregistry-cli/pull/50 It warrants more testing, but should be good to progress from there!

**Pull request closed without merging**
