### PR TITLE
Allow for distribution specific locations of environment.tar

### LINKED ISSUE #46: sregistry pull assumes bootstrap files in /usr/libexec
The sregistry docker and nvidia clients seem to assume that executable libraries are located in `/usr/libexec`. However, on our Debian 9 systems, they are located in `/usr/lib/x86_64-linux-gnu`:
```
SREGISTRY_CLIENT=nvidia sregistry pull pytorch:17.12
...
Exploding /usr/libexec/singularity/bootstrap-scripts/environment.tar
ERROR b'tar: /usr/libexec/singularity/bootstrap-scripts/environment.tar: Cannot open: No such file or directory\ntar: Error is not recoverable: exiting now\n'
```

The following diff solves the issue on our specific system:
```
--- a/sregistry/main/nvidia/pull.py
+++ b/sregistry/main/nvidia/pull.py
@@ -91,7 +91,7 @@ def pull(self, images, file_name=None, save=True, force=False, **kwargs):
         # Metadata and container guts must come first
         res = which('singularity')['message']
         libexec = res.decode('utf-8').replace('/bin/singularity\n','')
-        envtar = '%s/libexec/singularity/bootstrap-scripts/environment.tar' %libexec
+        envtar = '%s/lib/x86_64-linux-gnu/singularity/bootstrap-scripts/environment.tar' %libexec
         layers = [envtar] + layers
```

### PR DESCRIPTION
**Pull request by vsoch**
This PR will fix #46 , specifically the bug that sregistry was assuming that the environment.tar file (in bootstrap-scripts) was located according to the Linux Filesystem Hierarchy. Instead, we need to first check for this location, and if the file isn't found, fall back to checking via dpkg-architecture, and then as a final fall back we package the environment.tar with sregistry-cli. Since these are simple text files (with backwards compatibility) this should be a reasonable solution. @slefrancois I don't have the architecture to test this, would you be able to give it a test? Once these changes are good, this will be released as 0.0.7 on pip - the improvement in UI with nvidia:// and docker:// uris are important enough to warrant it.

### CODE REVIEW

**Comment by slefrancois** [comment]
I get the following error after layers have been downloaded:
```
Traceback (most recent call last):
  File "/u/lefransi/.local/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry', 'console_scripts', 'sregistry')()
  File "/u/lefransi/library/sregistry-cli/sregistry/client/__init__.py", line 319, in main
    subparser=subparsers[args.command])
  File "/u/lefransi/library/sregistry-cli/sregistry/client/pull.py", line 54, in main
    save=do_save)
  File "/u/lefransi/library/sregistry-cli/sregistry/main/nvidia/pull.py", line 92, in pull
    envtar = self._get_environment_tar()
  File "/u/lefransi/library/sregistry-cli/sregistry/main/docker/api.py", line 464, in get_environment_tar
    triplet = run_command(cmd).strip('\n')
AttributeError: 'dict' object has no attribute 'strip'
```

**Comment by vsoch** [comment]
Is this the same command as before?
```
SREGISTRY_CLIENT=nvidia sregistry pull pytorch:17.12
...
```
Are you using python2 or python3?

**Comment by slefrancois** [comment]
It works with the latest commit.

I was using python 3.6 and `SREGISTRY_CLIENT=nvidia sregistry pull tensorflow:17.12`.

**Comment by vsoch** [comment]
woohoo! If it is working and good and gets your approval, then I'm good to merge. I just tweaked the changelog and version so we don't go up quite so quickly - I'm more a fan of releasing quickly and often in response to need for fixes.

**Comment by slefrancois** [comment]
It works, I can pull from nvidia's docker cloud now with this PR.

I'm now testing GPU access with pytorch and tensorflow containers. It seems that if I build as root, I can only use the GPUs if I start the container as root.

I'll investigate a bit further first, but I think this belongs in a seperate issue/PR.

**Comment by vsoch** [comment]
I would test this first with just Singularity, and figure out if it's an issue with Singularity (issue [would go here](github.com/singularityware/singularity/issues)) or the download client. Let me know when you know more, and/or if this PR is good for merge on your end.

**Comment by vsoch** [comment]
Also with the update, you should be able to pull like:

```
sregistry pull nvidia://tensorflow:17.12
```
instead of setting the environment variable first. You could do that if you have a consistent client that you use, but I would expect switching between nvidia and docker to be pretty common!

**Comment by slefrancois** [comment]
`sregistry pull...` does work once I set my nvidia token in the environment.

As for the GPU issue, I'm using `singularity shell --nv nvidia-pytorch:17.12.simg` to run the container built by sregistry from the nvidia cloud.

I'm not sure if it's an issue with how sregistry builds the container from nvidia's docker layers, or how singularity runs those containers, or just my workflow. As I said it works fine if I build as root, then run as root, but not build as root, run as user. So it could be a permissions issue, especially since docker assumes containers are run as root.

Anyway, I think the current commits fulfill the PR's goals, so I'm for merging. Further investigation of how singularity interacts with the resulting image is probably another PR, possibly on singularity itself.

**Comment by vsoch** [comment]
Great! Thanks for your help with this. I agree with merge because it does improve the software, and we can continue with the other bugs in another issue.

**Comment by slefrancois** [comment]
Following up on this, the problem with GPU access was on my side. I had an installation of tensorflow in $HOME/.local that was getting mounted in the container. It was getting imported instead of the container version... I've restested nvidia's pytorch and tensorflow containers and they both work as root and as a regular user.

**Comment by vsoch** [comment]
woohoo! That's funny, I ran into that same issue on our cluster, and I didn't even know that .local folder existed for the longest time :)

**Comment by slefrancois** [comment]
`pip install --user` goes to .local by default. It's very high in the Python path priority, often going before conda environments for instance. So on clusters and networks where users don't have admin rights, it's pretty common to install high level libraries with pip as user.

There is some potential confusion in having the home folder mounted in the container by default. One would assume the container is a clean new environment, but mounting the home with user libraries can contaminate it. On the other hand, it's very convenient to have a persistent home mounted by default, so I'm not sure which is best (and it's outside the scope of this PR).

**Comment by vsoch** [comment]
Sorry I'm not sure what you are suggesting - if it's the case that the environment.tar cannot be found with Singularity and it defaults to the one provided by the package, you are saying this is an issue? The mounting of home sounds like an issue for Singularity, not for the client here --> https://www.github.com/singularityware/singularity/issues

If there is an issue with mounting by default please open an issue there!

**Comment by slefrancois** [comment]
It's the default mounting done by singularity, indeed not related to sregistry. Not sure I would call it an issue, more a design choice. I'll think about it and see if it's worth opening an issue on the singularity repo.

**Pull request merged**
