### PR TITLE
removing dateutils

### LINKED ISSUE #197: dateutils real requirement?
I am looking into creating a conda package for `sregistry` with as many options supported as possible and I ran into trouble with the `dateutils` package, which at least according to its [conda-forge package maintainers](https://github.com/conda-forge/dateutils-feedstock/blob/master/recipe/meta.yaml) appears not to support python 3.

I was wondering if this package is really a dependency anyway as I cannot find any usage of it in the codebase, including the `dateadd` and `datediff` scripts that it installs.

If you agree that it can be removed from the dependency list, I will gladly open a PR to do this.

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will remove dateutils, and thus support for Python 2*. A note is added to the readme about previous versions with Python 2.* support. This will allow for creating an install with conda, and will close #197 

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

### CODE REVIEW

**Comment by tschoonj** [comment]
Looks good, but strictly speaking the last release isn't really python 2.7 compatible either as it will choke on that `datetime.timezone` import. 😄

**Comment by vsoch** [comment]
I think so too - I never used it for Python 2.7 but I left a buffer of versions there if someone comes back and desperately needs for it to work.

**Comment by vsoch** [comment]
https://pypi.org/project/sregistry/0.2.0/

**Comment by tschoonj** [comment]
By the way you may also want to disable the Circle-CI python 2.7 build :wink:

**Pull request merged**
