### PR TITLE
Add/ceph backend

### PR DESCRIPTION
**Pull request by vsoch**
This PR will add a Ceph Storage backend, with options to:
 - push 
 - pull
 - search

### Links
 - docs :point_right:  [for the client usage](https://github.com/singularityhub/sregistry-cli/blob/ee9d69e94f3fa82f3c7fd0f1c1e97f7cfa387204/docs/clients/ceph.md) that will be rendered pretty on the website, right now the image links don't render given not there!
 - [ceph/swift python client](http://docs.ceph.com/docs/mimic/radosgw/swift/python/)

 @michaelmoore10 I think you would be best to test this out! I've written up the docs page to walk you through the functions - let's start dialog here about requested changes, questions, etc. If the documentation is missing or not clear on something that is important to know too! No rush on this! To scope our plan again, after we integrate this sregistry client I can develop an integration with sregistry server, and actually for any of the backends here (which already include Google Storage, AWS, etc.)

# Discussion

## Metadata

Right now I'm not happy with the metadata storage, specifically the image uri. For other storage (e.g., singularity hub) the metadata is stored both in the database and "hard coded" into the file names, so if you ever were to lose the database you'd still have everything through version and commit. I'd like to do a similar strategy here, and I see a few options:

 1. If ceph has a metadata API for storage, we can use it (and keep images storage as .simg so the objects look like files
 2. We could also completely represent the uri in just the file name, so again, if database is lost, and maybe metadata lost, the files have it.
 3. Combination of both of the above.

## Permissions

> What (user) or (users) of a ceph database interact with it from sregistry?

### Case 1. One Ceph User for Singularity Registry
The Ceph storage has one "master" singularity registry server permission, interaction with images is entirely based on the permissions logic from within sregistry (e.g., teams, owner of collection, etc.). This makes it easy / possible to interact with images from singularity registry, but it breaks in logic if/when you have a single user that wants to interact with storage from the command line, and isn't given that permission. You wouldn't want to share the Ceph Storage accounts for sure, but if you only intend for your cluster admin to be pushing images, this could work.

### Case 2: Each user has a predetermined permission set for the registry.
In this case, you would need to create a user in the Ceph Storage for each user in the registry, and then the "permissions check" would be a two level thing - if the user isn't added to a collection / team in singularity registry server to push / pull an image, it's not going to be allowed to push from the command line (we would check with the server first). If the user is added to a collection (a collaborator) but doesn't have permission for ceph storage, they would also be denied the push/pull. Both of these cases could lead to potential issue, because:

 1. for the first they could easily use a different tool to push content to the Ceph Storage, it just wouldn't be "seen" by singularity registry server. Maybe that's okay, because they might want to push other content anyway?
 2. For the second, a user could be added to the team with goal of collaboration, but denied access to pull the image.

To resolve the second, it could be that you limit write access to a set of users, and then you open up read access to the rest of the storage. Any containers that are to be shared would need to have read access.

I'm not privy to how a real deployment of a Ceph Storage is setup, but it could also be the case that SRegistry server is somehow linked to Ceph. For example, if you get user accounts from the same LDAP server, maybe that would be an  idea? I'm definitely open for discussion on this! Let me know your thoughts.

We want a balanced solution that doesn't place too much reliance of Singularity Registry on Ceph Storage, and vice versa, but we also want to reduce potential mismatch between users in both. This almost makes me think that we should consider them separate things - the Ceph Storage will have some set of users that can write content, and then Singularity Registry (in using ceph storage) gets a master "read access" to all of it, and then manages the "does user A have access to Container A" via its own permissions.  Let's keep in mind that whatever we decide here, we will also think about in context of other object stores (e.g., Google Cloud, AWS, etc.)

### CODE REVIEW

**Comment by vsoch** [comment]
And @michaelmoore10 a few quick notes - right now there is no metadata stored with the image in storage, is there a good way to do this? If not, we need to better capture version, etc. in the image name. Or just remove the .simg entirely so the object also serves as the uri. Let me know and I can update the PR.

**Comment by vsoch** [comment]
@michaelmoore10  it's been a month and I haven't heard from you. I'm going to merge and if you have issues you'll have to open another PR. As for the custom storage from sregistry, I won't be moving forward with this because it was reliant on your testing. Thanks anyway!

**Comment by michaelmoore10** [comment]
Hi Vanessa,

I apologize for not getting to test this yet.  Other projects needed my time, but this is on the top of my list to test and get you feedback.

-Mike

**Comment by vsoch** [comment]
Cool, thanks! Please open an issue with comments and/or feedback to address when you get some time.

**Pull request merged**
