### PR TITLE
sregistry.main.s3: add delete support

### PR DESCRIPTION
**Pull request by tschoonj**
Also:
 * sregistry.main.[registry,s3].pull: fix early return

### CODE REVIEW

**Comment by vsoch** [comment]
LGTM - if you've tested and this is ready to go, could you please add a note to the CHANGELOG and bump the version?

**Comment by tschoonj** [comment]
I ran some tests and it appears to work fine.

The version has been bumped and the changelog updated

**Comment by vsoch** [comment]
Awesome, let's merge!

**Comment by vsoch** [comment]
https://pypi.org/project/sregistry/0.2.12/

**Comment by tschoonj** [comment]
Thanks! I already closed the conda-forge PR...

**Pull request merged**
