### PR TITLE
Add AWS (S3) and Minio Client

### PR DESCRIPTION
**Pull request by vsoch**
This PR will add Amazon S3 (tested with Minio) support to Singularity Registry Client. It will address the issue here https://github.com/singularityhub/sregistry/issues/160

@fenz would you care to test? I've generated some docs (that will be rendered in the web docs when merged). I did this quickly so please test carefully and let me know if there is functionality or docs that are not up to speed / could be improved! Happy Friday!

[sregistry-s3.pdf](https://github.com/singularityhub/sregistry-cli/files/2704643/sregistry-s3.pdf)

### CODE REVIEW

**Comment by fenz** [comment]
Sorry for the late reply. As first comment, if you start the sregistry-cli in a container you can't communicate with the Minio using the "localhost" endpoint but it is working using the other endpoint listed by Minio when it starts (http://172.17.0.2:9000 in this case) so it would maybe be better to mention this in the docs. 
I have also a question about the "sregistry search", is there a reason why it is not always showing the size of the images?
I'll need some more time to test it better, in the meanwhile I wish you a great end of the year and beginning of new one!

**Comment by vsoch** [comment]
When you started the mini container, did you map to localhost? For example, when I do docker ps I see:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                PORTS                          NAMES
aaa8fbda0d8e        minio/minio         "/usr/bin/docker-ent…"   7 days ago          Up 7 days (healthy)   0.0.0.0:9000->9000/tcp         xenodochial_wiles
```
Note that the command to run was:

```
docker run -p 9000:9000 -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 minio/minio server /data
```
I think I can add the size for you, give me a few minutes to test.

**Comment by fenz** [comment]
The port it's exposed (-p 9000:9000) but I could not access Minio on the localhost from within another container, is it working for you? Regarding the size, in the docs there's the output for the "sregistry search" command and the size is not shown for all of the images (it is missing the size of the first image for example). I pulled the Ubuntu:latest from docker (using the sregistry docker client) and pushed the same to the S3 bucket (using the sregistry S3 client). I'll try to build an image and then push it, I'll let you know if I get any difference.

**Comment by vsoch** [comment]
If you are *in* another container on the localhost and not using docker-compose, there is no way for the second contacted to be linked. The expected use case based on the docs (and using one Docker container without Docker compose) is that you are accessing in the browser on the local machine running Docker. This works for me.

The pushed images, using sregistry that are on your host, should have a size. You can try adding a print to main/s3/push.py to see the metadata that is added to get a better sense of what is going on.

**Comment by fenz** [comment]
Maybe is anyway not so important as discussion (because Minio is just for testing) but let me write down all the steps I did.
## Minio Storage Server
1. Start Minio as docker container:
`docker run -p 9000:9000 -e MINIO_ACCESS_KEY=minio -e MINIO_SECRET_KEY=minio123 minio/minio server /data`

**Output:**
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000
...
## Sregistry client
1. Clone github repo:
`git clone https://github.com/singularityhub/sregistry-cli`
2. Switch to aws-push branch
`git checkout add/aws-push`
3. Build a docker image from the Dockerfile
`docker build -t sregistry-cli:s3 .`
4. Start a shell in the docker container
`docker run --rm -it --entrypoint "/bin/bash" --privileged sregistry-cli:s3`
5. Pull an image from docker
`SREGISTRY_CLIENT=docker sregistry pull ubuntu:latest`
Path: /root/.singularity/shub/library-ubuntu-latest.simg
6. Setup S3 object store
`SREGISTRY_S3_BASE=http://127.0.0.1:9000`
`SREGISTRY_S3_BUCKET=mybucket`
`AWS_ACCESS_KEY_ID=minio`
`AWS_SECRET_ACCESS_KEY=minio123`
`export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY SREGISTRY_S3_BASE SREGISTRY_S3_BUCKET`
7. Push image to S3
`SREGISTRY_CLIENT=s3 sregistry push --name test/ubuntu:latest /root/.singularity/shub/library-ubuntu-latest-latest.simg`
**Output:**
....
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://127.0.0.1:9000/"
8. Update Object store Endpoint:
`export SREGISTRY_S3_BASE=http://172.17.0.2:9000`
9. Push image to S3 (second try)
`SREGISTRY_CLIENT=s3 sregistry push --name test/ubuntu:latest /root/.singularity/shub/library-ubuntu-latest-latest.simg `
**Output:**
[client|s3] [database|sqlite:////root/.singularity/sregistry.db]
[bucket:s3://s3.Bucket(name='mybucket')]
10. Search images
`SREGISTRY_CLIENT=s3 sregistry search`
**Output:**
[client|s3] [database|sqlite:////root/.singularity/sregistry.db]
[bucket:s3://s3.Bucket(name='mybucket')]
Containers
1  test/ubuntu:latest.simg	12-29-2018

I manually run the 2 containers on the same machine and it is working if I use the "172..." Endpoint.
The images size it is not shown but I will try to add a print as you suggested and try to understand it better.
Thanks a lot for your support.

**Comment by vsoch** [comment]
Your issue makes perfect sense! This container has no sense of (your) localhost:
```
docker run --rm -it --entrypoint "/bin/bash" --privileged sregistry-cli:s3
```
I think we might be able to put together an example with docker-compose - I'll make some time for this tomorrow! Did you try running the sregistry client on your local machine or you must use a Docker container?

**Comment by vsoch** [comment]
Totally forgot to do this today! Tomorrow!

**Comment by vsoch** [comment]
hey @fenz I got it working! I wrote you up a little readme too, would you care to try it out? :point_right: https://github.com/singularityhub/sregistry-cli/tree/add/aws-push/examples/docker

This was a great idea, it's so much easier than having to manually walk through the steps to export all the variables. If it's good and we are ready to merge, I'll add this small tutorial to the docs, and later today will share with others to try.

**Comment by vsoch** [comment]
I'm going to say this looks good and merge. Thanks @fenz !

**Comment by vsoch** [comment]
Thanks again @fenz, for future notes, I did a writeup of the docker-compose deployment that is more user friendly --> https://vsoch.github.io/2019/sregistry-minio/

**Comment by fenz** [comment]
Sorry for the late reply (I'm just back from Christmas break). 
First of all thanks for your great effort! I have few comments.
1. docker-compose
    You are using the image: vanessa/sregistry-cli:add_aws-push, this is working because it exists in DockerHub but it is somehow connected with the temp branch that I guess you deleted after the merge, so you can maybe use the "latest" tag in the docker-compose (I tested it and it works as expected).
2. Documentation (https://singularityhub.github.io/sregistry-cli/client-s3)
    In the section "Push to Minio" the push command at the beginning is repeated:
    ```
    sregistry push --name test/ubuntu:latest /root/.singularity/shub/library-ubuntu-latest-latest.simg
    (base) root@c512453bfeed:/code# sregistry push --name test/ubuntu:latest /root/.singularity/shub/library-ubuntu-latest-latest.simg
    ```
3. Container size:
    As you suggested, I put some prints to understand the metadata and I maybe found the reason why the size is not shown.
    This is how you push the metadata into the bucket:
    ```
    # Create extra metadata, this is how we identify the image later
        metadata = {'sizemb': "%s" % image_size,
                    'client': 'sregistry' }
    ```
    Adding a print into pull.py:
    ```
    if found != None:
            metadata = found.get()['Metadata']
            print(metadata)
    ````
    I have this output:
    ```
    (base) root@6e0c0eeff03c:/code# sregistry pull test/ubuntu:latest.simg
    [client|s3] [database|sqlite:////root/.singularity/sregistry.db]
    [bucket:s3://s3.Bucket(name='mybucket')]
    {'Client': 'sregistry', 'Sizemb': '29'}
    [container][new] test/ubuntu-latest
    Success! /root/.singularity/shub/test-ubuntu-latest.simg
    ```
    At the beginning it looked ok but adding a print into query.py:
    ```
       if 'sizemb' in subsrc.metadata:
           size = '%sMB' % subsrc.metadata['sizemb']
           print(size)
    ```
    I was not getting any output, so I added the code from pull.py to check the metadata:
    ```
    metadata = subsrc.get()['Metadata']
       print(metadata)
    ```
    output:
    ```
    sregistry search
    [client|s3] [database|sqlite:////root/.singularity/sregistry.db]
    [bucket:s3://s3.Bucket(name='mybucket')]
    {'Client': 'sregistry', 'Sizemb': '29'}
    {'Client': 'sregistry', 'Sizemb': '29'}
    Containers
    1  test/ubuntu:lat.simg	1-7-2019	
    2  test/ubuntu:latest.simg	1-7-2019	
    ```
    only at this point I figured out the capital letter for 'Sizemb'.
    So, I have no idea how could it be (because you clearly push it as 'sizemb') but it seems at certain point it become 'Sizemb' and it doesn't get printed.

I hope this helps. 
Sorry again for my late reply.

**Comment by harshavardhana** [comment]
> It does appear to (still) be a bug that Minio isn't compatible with S3

To clarify this is an issue with boto3, not Minio. Better implemented libraries which handle this cleanly are aws-sdk-java and aws-sdk-go.

**Comment by vsoch** [comment]
Comment adjusted! Thanks @harshavardhana

**Pull request merged**
