### PR TITLE
Update/progress bar

### PR DESCRIPTION
**Pull request by vsoch**
This will hide the progress bar if the user adds `--quiet` to the client for push or pull:

```
$ sregistry --quiet pull shub://vsoch/hello-world

[container][update] vsoch/hello-world:latest@ed9755a0871f04db3e14971bec56a33f
Success! /home/vanessa/.singularity/shub/vsoch-hello-world:latest@ed9755a0871f04db3e14971bec56a33f.simg
```
On merge this will be version 0.0.97 of the client.

### CODE REVIEW

**Comment by vsoch** [comment]
Just was able to bring up an instance and test! I fixed a bug that I needed to pass the quiet variable to the callback function as a variable. The --quiet arg also seemed to work ok!

**Comment by victorsndvg** [comment]
I've tested it and it works as expected. Thanks @vsoch !

Remember that you have credentials to use our sregistry for your tests! :)

**Comment by vsoch** [comment]
Awesome! Merging. This will be released on pypi shortly after.

**Comment by vsoch** [comment]
https://pypi.org/project/sregistry/0.0.97/

**Pull request merged**
