### PR TITLE
Remove/sqlalchemy

### PR DESCRIPTION
**Pull request by vsoch**
Equivalent to #54 but to development (I forget which one I was encouraging myself to do, lol)

### CODE REVIEW

**Comment by vsoch** [comment]
okay @dctrud both PRs here have been updated - I didn't expose this as a command line argument because I don't want it to be easy (to discourage general use, or discovery!)

**Comment by vsoch** [comment]
actually hang on I want to implement it a little more elegantly

**Comment by vsoch** [comment]
okay @dctrud I think most of the ducks are in order, I need to do better at the order (and to which branches) I do PR to - I haven't been consistent (mostly PRing change branches to master) but now that there are a few of those it's getting messy. Bad practice on my part!

**Comment by dctrud** [comment]
'fraid this is a nope - let me look at it and I'll paste a diff here that makes it work.

```
SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull shub://sregistry.biohpc.swmed.edu/dtrudgian/ubuntu:latest
[client|hub] [database|sqlite:////home2/dtrudgian/.singularity/sregistry.db]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
Traceback (most recent call last):
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by dctrud** [comment]
Hmmm - I'm confused here - if I print the URL it's trying to go to, it's always trying to go to Singularity Hub...

```
$ SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull dtrudgian/ubuntu:latest
[client|hub] [database|sqlite:////home2/dtrudgian/.singularity/sregistry.db]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::

https://www.singularity-hub.org/api/container/dtrudgian/ubuntu:latest

$ SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull shub://sregistry.biohpc.swmed.edu/dtrudgian/ubuntu:latest
[client|hub] [database|sqlite:////home2/dtrudgian/.singularity/sregistry.db]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::

https://www.singularity-hub.org/api/container/sregistry.biohpc.swmed.edu/dtrudgian/ubuntu:latest




```

**Comment by dctrud** [comment]
Ahh - my fault, it does work... I missed the bit on sregistry/pull/77 about the 'registry' nesting for the token bit in `~/.sregistry' - and use a registry url

```
$ sregistry pull registry://dtrudgian/ubuntu:latest
[client|registry] [database|sqlite:////home2/dtrudgian/.singularity/sregistry.db]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Progress |===================================| 100.0% 
[container][update] dtrudgian/ubuntu:latest
Success! /home2/dtrudgian/.singularity/shub/dtrudgian-ubuntu:latest.simg
```

This is getting *really* confusing now though, using registry:// here, but shub://myregistry.org/ with singularity. I'm going to stick with the old singularity-python client at the moment, until everything matches up between the urls in the sregistry server 'usage' page, and what works with sregistry-cli

**Comment by vsoch** [comment]
Could you please review the PR? I put a lot of work into it. Singularity Registry global Client is intended to work across these different storage places. Interacting with Singularity Hub is actually very different than a Registry, and the only difference between the commands (for the user) is giving the URI. The reason the documentation tutorials just show `sregistry pull` is because they **first** show that the `SREGISTRY_CLIENT=registry` variable is exported. It's up to the user if they want to set this globally (e.g., export it) or on a per container basis (e.g., with registry://). Could we discuss your frustration and how this could be better? Singularity Python (sregistry) is going to go away with the next update, so we should work on this client to meet your needs. I'm sorry you don't like it. :(

**Comment by vsoch** [comment]
Don't forget that this PR was adding the option to remove the sqlalchemy database, which is a great feature I think!

**Comment by dctrud** [comment]
@vsoch - very sorry, that was very badly worded by me... I don't mean that this isn't valuable work and the right way to go. I meant I'll keep sregistry-python on the HPC cluster for our users for the moment. I think my only concern really is that keeping a nice sync between stuff in the sregistry web app side, and this is gonna be really important.

I am also looking at the PR with regard to other stuff implemented and will comment on the sqlalchemy removal in a minute.

I must also admit I didn't read the tutorials super carefully here - I was just trying what appeared on the sregistry website, which doesn't mention the SREGISTRY_CLIENT value here, or registry:// URI - and the token json it generates needs editing for use with sregistry-cli:

screenshot from 2018-01-26 14-42-04

**Comment by vsoch** [comment]
Oh yes these are good points! Right now, Singularity Registry doesn't know a thing about the client, mainly because it was developed after. I'll open an issue to fix this up.

**Comment by dctrud** [comment]
If I remove sqlalchemy from my conda environment I get:

```
$ SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull registry://dtrudgian/ubuntu:latest
WARNING Singularity is not installed, function might be limited.
Traceback (most recent call last):
  File "/home2/dtrudgian/.local/bin/sregistry", line 11, in <module>
    load_entry_point('sregistry==0.0.64', 'console_scripts', 'sregistry')()
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/sregistry-0.0.64-py3.4.egg/sregistry/client/__init__.py", line 265, in main
    from sregistry.main import Client as cli
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/sregistry-0.0.64-py3.4.egg/sregistry/main/__init__.py", line 115, in <module>
    Client = get_client()
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/sregistry-0.0.64-py3.4.egg/sregistry/main/__init__.py", line 105, in get_client
    from sregistry.database.dummy import ( add )
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/sregistry-0.0.64-py3.4.egg/sregistry/database/__init__.py", line 1, in <module>
    from .models import *
  File "/home2/dtrudgian/.local/lib/python3.4/site-packages/sregistry-0.0.64-py3.4.egg/sregistry/database/models.py", line 24, in <module>
    from sqlalchemy import (
ImportError: No module named 'sqlalchemy'
```

Don't think this is a problem with the code added, rather that you have imports in `sregistry/database/__init.py__` so are being pulled into the package namespace when going down through to load `sregistry.database.dummy`

I can make it run with this diff:

``` diff
diff --git a/sregistry/database/__init__.py b/sregistry/database/__init__.py
index 18525c8..83d2a8c 100644
--- a/sregistry/database/__init__.py
+++ b/sregistry/database/__init__.py
@@ -1,8 +1,8 @@
-from .models import *
-from .sqlite import ( 
-    add, get, rm, rmi, images, 
-    inspect,
-    get_container,
-    get_collection,
-    get_or_create_collection 
-)
+#from .models import *
+#from .sqlite import ( 
+#    add, get, rm, rmi, images, 
+#    inspect,
+#    get_container,
+#    get_collection,
+#    get_or_create_collection 
+#)
diff --git a/sregistry/main/__init__.py b/sregistry/main/__init__.py
index 4b388f0..b3eb085 100644
--- a/sregistry/main/__init__.py
+++ b/sregistry/main/__init__.py
@@ -104,6 +104,8 @@ def get_client(image=None):
     else:
         from sregistry.database.dummy import ( add )
         Client.add = add
+        # speak needs Client.database
+        Client.database = "Dummy"
 
     # Initialize the database
     cli = Client()

```

So a conditional around the imports in `sregistry/database/__init__.py` is needed, or could remove the dummy database into a separate `sregistr.dummydatabase`

Then need to set Client.databas so speak() is happy - then it works nicely :-)

```
$ SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull registry://dtrudgian/ubuntu:latest
[client|registry] [database|Dummy]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Progress |===================================| 100.0% 
Success! dtrudgian-ubuntu:latest.simg
```

**Comment by dctrud** [comment]
:+1: Looks good to me. No db backend and force no verify of ssl working nicely... thank you!

```
$ SREGISTRY_HTTPS_NOVERIFY=TRUE sregistry pull registry://dtrudgian/ubuntu:latest
WARNING Singularity is not installed, function might be limited.
WARNING Singularity is not installed, function might be limited.
[client|registry] [database|dummy]
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
WARNING Verify of certificates disabled! ::TESTING USE ONLY::
/home2/dtrudgian/.local/lib/python3.4/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Progress |===================================| 100.0% 
Success! dtrudgian-ubuntu:latest.simg
```

**Comment by vsoch** [comment]
okay, merging! I'll see what happens when I PR this against master after, and then figure out the right way to do this next time.

**Comment by vsoch** [comment]
@dctrud see this commit for the addition to the "commands" page for the sregistry client!

https://github.com/singularityhub/sregistry/commit/b27283af9b34e1a12d3fdff58e88a9a7c5759299

**Comment by dctrud** [comment]
@vsoch - awesome. Thanks for indulging my confusion.

**Comment by vsoch** [comment]
I'm really glad we moved this as a dependency - it wasn't needed and I just never thought about it.

**Pull request merged**
