### PR TITLE
Add/backends and remove "remote" command.

### LINKED ISSUE #66: [sregistry login] to set default client and add credential, other
SRegistry login should allow a user to:

1. set a default client to use, and 
2. if there are token / other needed and they aren't in the secrets, the user should be prompted.

### PR DESCRIPTION
**Pull request by vsoch**
This pull request will remove the "remote record" command group (not so useful) and add a `backend` command group to make interaction with the various backend clients much easier and close #66. Currently, the user can specify the client via export / definition of an environment variable, or via the uri in a command:

```bash
# Option 1: one off command
SREGISTRY_CLIENT=globus sregistry shell

# Option 2: group of commands and specification via environment
SREGISTRY_CLIENT=globus
export SREGISTRY_CLIENT

# Option 3: Unique Resource Indentifier
sregistry pull shub://vsoch/hello-world
```
This PR adds a fourth option that allows the user to explicitly activate the endpoint, deactivate any active, list endpoints or a status, or remove settings for an endpoint. Here are the newly added notes in the docs:

```bash
$ sregistry backend
usage: sregistry backend [-h] [commands [commands ...]]

positional arguments:
  commands    activate, deactivate, ls, status, rm a client

optional arguments:
  -h, --help  show this help message and exit

             sregistry backend ls:     list backends found in secrets
             sregistry backend status: get status
             sregistry backend rm <backend> remove a backend
             sregistry backend de|activate: activate or deactivate
```

We could get a status at any time

```bash
$ sregistry backend status
[backend status]
There are 9 clients found in secrets.
active: globus
```

We could also do a listing to see how more comprehensive list:

```bash
$ sregistry backend ls
Backends Installed
google-storage
nvidia
dropbox
registry
google-drive
globus
google-compute
hub
```

You can ask for a detailed listing for a specific backend:

```
$ sregistry backend ls dropbox
dropbox
{
    "SREGISTRY_DROPBOX_TOKEN": "xxxxxxxxxxxxxxxxxxxxxx"
}
```

You can remove (`rm`) a backend from the credential file:

```bash
$ sregistry backend rm docker
[remove] docker
```
```bash
$ sregistry backend ls docker
docker is not a known client.
Backends Installed
nvidia
globus
registry
hub
google-storage
google-drive
dropbox
google-compute
```

Finally, you can get a current status, activate a particular backend to be used as the client,
or deactivate so none are selected.

```bash
$ sregistry backend status
[backend status]
There are 8 clients found in secrets.
There is no active client.
```
```bash
$ sregistry backend activate globus
[activate] globus
```
```bash
$ sregistry backend status
[backend status]
There are 9 clients found in secrets.
active: globus
```

This activated approach takes preference to using the default client (Singularity Hub) but does
not override any specification that you set in the environment or on the command line with a unique
resource identifier.

@remyd1 please take a look and see how you like it! When it is satisfactory we will merge and release as version 0.0.84 on pypi.

### CODE REVIEW

**Comment by remyd1** [comment]
Hi @vsoch 

A big :+1: !

Finally, no `backend add <backend> <username> <token>` ?

**Comment by vsoch** [comment]
okay added, please review.

**Comment by vsoch** [comment]
okay one more update - I changed "rm" to delete (which seems more appropriate) and added remove / rm in order to remove a setting (the opposite of add).

**Comment by remyd1** [comment]
Some comments:

  -  `sregistry backend rm <backend>` take an additonnal argument. I don't see why ..? eg:
  `sregistry backend rm hub`
  ```
  Usage: sregistry backend remove <backend> <variable>
  ````
  `sregistry backend remove hub base`
  ```
  [remove]
  SREGISTRY_HUB_BASE
  ```
  But that last command does not seem to have any effect:
  ```
  sregistry backend ls                                              
  None is not a known client.
  Backends Installed
  hub
  registry
  ```
  
  - `ls` is for listing, but can also `show` a specific registry content. That is not obvious. Maybe you could add a special subcommand `show` for this purpose.
  
  - `ls` is listing the number of repositories but when you activate one, it automatically add 1 to the sum of total repositories.

  - I tried the `add`. It works, but I think the syntax is not the one I used:
  ```
  # after deactivating hub and removing it
  sregistry backend add hub "base" "https://singularity-hub.org/api"
  sregistry backend ls hub
  hub
  {
    "SREGISTRY_HUB_BASE": "https://singularity-hub.org/api"
  }
  ```

  - Finally, when the json is malformed, I only get an error message from the json python library. Maybe catching these errors and print a more friendly message before could be useful.

Kind regards,
Rémy

**Comment by vsoch** [comment]
to make the "ls <client>" more clear, I added it to the usage as an example:

```bash
vanessa@vanessa-ThinkPad-T460s:~/Documents/Dropbox/Code/sregistry/sregistry-cli$ sregistry backend 
usage: sregistry backend [-h] [--force] [commands [commands ...]]

positional arguments:
  commands     activate, deactivate, ls, status, rm a client

optional arguments:
  -h, --help   show this help message and exit
  --force, -f  force add if variable exists.

             sregistry backend ls:     list backends found in secrets
             sregistry backend ls hub
             sregistry backend status: get status
             sregistry backend rm <backend> remove a backend
             sregistry backend de|activate: activate or deactivate
             sregistry backend remove nvidia token
             sregistry backend add nvidia token 123455
               
             SREGISTRY_NVIDIA_TOKEN 123455
```

**Comment by remyd1** [comment]
Concerning the `rm` subcommand, the default `.sregistry` file contains:
```
{
    "SREGISTRY_CLIENT": "hub",
    "hub": {
        "base": "https://singularity-hub.org/api"
    }
}
```
Mine is:
{
  "hub": {
        "base": "https://singularity-hub.org/api"
    },
    "registry": {
        "token": "...",
        "username": "remy",
        "base": "http://...."
    },
  "SREGISTRY_CLIENT": "hub"
}


I thought the standard way to remove it was:

```
sregistry backend remove hub base                    
[remove]
SREGISTRY_HUB_BASE

sregistry backend ls
None is not a known client.
Backends Installed
registry
hub

sregistry backend ls hub
hub
{
    "base": "https://singularity-hub.org/api"
}
````

I don't find the corresponding doc about this, except here (or in the basic help `sregistry backend --help`):
```
sregistry backend rm docker
[remove] docker
```

However, `delete` works as expected:
```
sregistry backend delete hub
[delete] hub
sregistry backend ls hub                             
hub is not a known client.
Backends Installed
registry
```

But, in fact, `hub` is still here and available:
```
sregistry search cuda
[client|hub] [database|sqlite:////home/remy/.singularity/sregistry.db]
1  https://www.singularity-hub.org/containers/1785      shahzebsiddiqui/eb-singularity:cuda-9.0.176
2  https://www.singularity-hub.org/containers/1001      marcc-hpc/anaconda-cuda:latest
3  https://www.singularity-hub.org/containers/1160      tin6150/cuda:latest
4  https://www.singularity-hub.org/containers/2273      csadorf/singularity-recipes:cuda8-openmpi3.0
5  https://www.singularity-hub.org/containers/2272      csadorf/singularity-recipes:cuda8
6  https://www.singularity-hub.org/containers/2274      csadorf/singularity-recipes:cuda8-ml
7  https://www.singularity-hub.org/containers/2269      ucr-singularity/cuda-9.0-base:latest
8  https://www.singularity-hub.org/containers/2394      aizjForever/darch_recipe:cuda
```
I suppose it is because this is the default repository.

Rémy.

**Comment by vsoch** [comment]
Okay, I fixed up the issues with removing things. Here I am removing the hub base (not really recommended...)

```
sregistry backend remove hub base
[remove]
BASE
$ sregistry backend ls hub
hub
{
    "SREGISTRY_SHELL": "ipython"
}
```
Removing or editing the configuration file does not delete a client in the way you are thinking - these are folders and files in the python install that are always present. All it does is remove it from the settings file, or otherwise update that. When you first install for a particular client, you also aren't adding extra files - you are just installing the extra package dependencies for that client.

**Comment by remyd1** [comment]
Ok. About removing `hub`: yes, I know it is not recommanded, it was just for the test.

Concerning the `search`, if the repository is not in the setting, I don't see why it should continue to search on these repositories. I think this behavior is a bit confusing for the users. If you are just managing python dependencies, you "just" have to check the settings before importing (- or not -) the needed files.

**Comment by remyd1** [comment]
I see. Ok, nevermind. This would need to many things to be changed.

I was not talking about deleting anything on the client, just changing the way existing functions are actually working (specifically, `get_client` from [here](https://github.com/singularityhub/sregistry-cli/blob/master/sregistry/main/__init__.py). ). One more time, in fact, I think the shub, which is the default, is confusing; Indeed:
```
'''
[...]
If there is no preference, the default is to load the singularity 
       hub client.
[...]
'''
```

Rémy

**Comment by remyd1** [comment]
You can merge.

Thanks !

**Comment by vsoch** [comment]
woot! Merging!

**Pull request merged**
