### PR TITLE
Add Keystone authentication support for Swift client

### PR DESCRIPTION
**Pull request by michaelmoore10**
The swift client support only used Legacy Authentication per [The swiftclient.Connection API](https://docs.openstack.org/python-swiftclient/latest/client-api.html)
docs. This does not work for environments that use Openstack Keystone as a 
centralized authentication service.  This change implements the support for 
Keystone V2 and V3 authentication along with Openstack's Pre-Authenticated 
Token access to object storage.

To enable this support, we require several additional parameters:

SREGISTRY_SWIFT_AUTHTYPE: Defines the type of authentication
        Expected Values: 'preauth', 'keystonev3', 'keystonev2',
                                   or blank (Legacy Auth)

Required variables for 'preauth" authentication type"
SREGISTRY_SWIFT_OS_AUTH_TOKEN: Token Pre-Authentication access - Different
                                                         token from the SREGISTRY_SWIFT_TOKEN
SREGISTRY_SWIFT_OS_STORAGE_URL: Authenticated URL to access the bucket
                                                          directly.  This is not the URL to authenticate

Required variables for 'keystonev3' authentication:
SREGISTRY_SWIFT_USER - Username that is authenicating against Keystone
SREGISTRY_SWIFT_TOKEN - User Password/Token for the specified user
SREGISTRY_SWIFT_URL - URL for the Keystone authentication service

Required variables for 'keystonev2' authentication:
SREGISTRY_SWIFT_USER - Username that is authenicating against Keystone
SREGISTRY_SWIFT_TOKEN - User Password/Token for the specified user
SREGISTRY_SWIFT_URL - URL for the Keystone authentication service
SREGISTRY_SWIFT_TENANT - Tenant Name in keystone that the user has access to
SREGISTRY_SWIFT_REGION - The region that the tenant is stored in

Required variables for legacy authentication:
SREGISTRY_SWIFT_USER - Username that is authenicating against the object store
SREGISTRY_SWIFT_TOKEN - User Password/Token for the specified user
SREGISTRY_SWIFT_URL - URL for the object storage authentication service

Added documentation to describe how to use Keystone v2/v3 and
per-authenticated token access.

### CODE REVIEW

**Comment by michaelmoore10** [comment]
I have tested out Keystone V2 and Keystone Token authentication in our environment.  I do not have the ability to test Keystone V3 currently, so the support for it, while mostly complete according to the API docs, may not be sufficiently complete.

Testing Env:  CentOS 7.4 running Miniconda 3.7.1 and Singularity 2.6.1

**Comment by vsoch** [comment]
hey @michaelmoore10 is there any way for me to test this out? The documentation looks good, and if you can confirm working (since you are the primary user) your testing would be sufficient. If other users test and find bugs they can open issues. Thoughts?

**Comment by michaelmoore10** [comment]
Hi @vsoch 
I don't have a means to allow you to test.  Our object storage environment is internal to our organization.  I have validated the keystonev2 and pre-authenticated token access methods against our production environment. They do work as expected.  

I included keystonev3 just to be complete with the documentation from openstack, but our environment is not configured for v3 so it should be considered little more than a stub.  It may only need a few additional environment value to be set to be operable.

If other users test this out and have problems, I would be happy to resolve any issues reported.

**Comment by vsoch** [comment]
okay, then I'm good with merging. Could you please update the sregistry/version.py (bump up the version) and add a line to CHANGELOG.md  in the root to reflect the changes? I will release after that.

**Comment by michaelmoore10** [comment]
Quick question.  In the changelog, do the numbers at the end of a line in parenthesis correspond to the __version__ string in sregistry/version.py?

**Comment by vsoch** [comment]
yes, it should be the same! if you are having trouble just don't worry about it - I'll merge and then do another PR to update the version and changelog. You've already done great work and help and don't need to worry about these release details.

**Comment by vsoch** [comment]
Perfect! Merging, and will post link to pypi release shortly thereafter.

**Comment by vsoch** [comment]
Thanks for your hard work on this @michaelmoore10 !

https://pypi.org/project/sregistry/0.1.33/

**Pull request merged**
