### PR TITLE
added max_version to sqlalchemy

### PR DESCRIPTION
**Pull request by iferres**
Addressing #264. I tested it by building the Singularity file but pointing to my fork, and it looks like it works although I get:
```
apptainer shell --cleanenv sregistry.sif                          
Apptainer> sregistry images
WARNING Singularity is not installed, function might be limited.
```
which I think it's because can't install singularity inside another singularity.
Let me know.

### CODE REVIEW

**Comment by vsoch** [comment]
> which I think it's because can't install singularity inside another singularity.

Yes that's correct! That warning might be a bit heavy handed - I've definitely noticed it printed a lot. If you want to change the verbosity we could look into that - ideally it just gets printed once (and not again).

**Comment by vsoch** [comment]
It’s formatting - you need to run black 23.3.0. Look at the CI logs to verify.

**Review by vsoch — APPROVED** [review]
Thank you!

**Comment by iferres** [comment]
Thanks to you! And for your patience. Bests!

**Pull request merged**
